version: '3.8'
services:
  app:
    build: .
    ports:
      - "6660:8080"
    environment:
      DB_HOST: postgres_postgres_1
      DB_PORT: 5432
      DB_USER: permutations_user
      DB_PASS: 423kjFKDH98fsd
      DB_NAME: permutations_db 
networks:
  default:
    external: true
    name: postgres_default 